[development]
address = "localhost"
port = 8000
# workers = [number_of_cpus * 2]
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 5012
# workers = [number_of_cpus * 2]
workers = 4
log = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
